INSERT INTO sponsoredlinks_group VALUES (1,'theme01','tag1 tag2 tag3');
INSERT INTO sponsoredlinks_group VALUES (2,'theme02','tag4 tag5');
INSERT INTO sponsoredlinks_group VALUES (3,'theme03','tag6 tag7 tag8');
INSERT INTO sponsoredlinks_group VALUES (4,'theme04','tag9');
INSERT INTO sponsoredlinks_group VALUES (5,'theme05','tag10 tag11');
INSERT INTO sponsoredlinks_group VALUES (6,'theme06','tag12 tag13 tag14 tag16 tag17');
INSERT INTO sponsoredlinks_group VALUES (7,'theme07','tag18 tag19');
INSERT INTO sponsoredlinks_group VALUES (8,'theme08','tag20 tag21 tag22');
INSERT INTO sponsoredlinks_group VALUES (9,'theme09','tag23 tag24');
INSERT INTO sponsoredlinks_group VALUES (10,'theme10','tag25 tag24 tag27');
INSERT INTO sponsoredlinks_group VALUES (11,'theme11','tag28');
INSERT INTO sponsoredlinks_group VALUES (12,'theme13','tag30 tag31');
INSERT INTO sponsoredlinks_group VALUES (13,'theme14','tag32 tag33 tag34 tag36 tag37');
INSERT INTO sponsoredlinks_group VALUES (14,'theme15','tag38 tag39');

INSERT INTO sponsoredlinks_template VALUES (1, 'fiche élu', 'document/fiche_elu');
INSERT INTO sponsoredlinks_template VALUES (2, 'comarquage', 'comarquage');
INSERT INTO sponsoredlinks_template VALUES (3, 'article', 'document/article');

INSERT INTO sponsoredlinks_set VALUES(1, 'bloc01', 1);
INSERT INTO sponsoredlinks_set VALUES(2, 'bloc02', 2);
INSERT INTO sponsoredlinks_set VALUES(3, 'bloc03', 3);
INSERT INTO sponsoredlinks_set VALUES(4, 'bloc04', 4);
INSERT INTO sponsoredlinks_set VALUES(5, 'bloc05', 5);
INSERT INTO sponsoredlinks_set VALUES(6, 'bloc06', 6);
INSERT INTO sponsoredlinks_set VALUES(7, 'bloc07', 7);
INSERT INTO sponsoredlinks_set VALUES(8, 'bloc08', 8);
INSERT INTO sponsoredlinks_set VALUES(11, 'bloc11', 11);
INSERT INTO sponsoredlinks_set VALUES(12, 'bloc12', 12);
INSERT INTO sponsoredlinks_set VALUES(13, 'bloc13', 13);
INSERT INTO sponsoredlinks_set VALUES(14, 'bloc14', 14);

INSERT INTO sponsoredlinks_link VALUES(1, 1, 'http://www.mairie.fr/document/fiche_elu/1');
INSERT INTO sponsoredlinks_link VALUES(1, 2, 'http://www.mairie.fr/comarquage/1');
INSERT INTO sponsoredlinks_link VALUES(1, 3, 'http://www.mairie.fr/document/article/1');
INSERT INTO sponsoredlinks_link VALUES(2, 1, 'http://www.mairie.fr/document/fiche_elu/2');
INSERT INTO sponsoredlinks_link VALUES(2, 2, 'http://www.mairie.fr/comarquage/2');
INSERT INTO sponsoredlinks_link VALUES(2, 3, 'http://www.mairie.fr/document/article/2');
INSERT INTO sponsoredlinks_link VALUES(3, 1, 'http://www.mairie.fr/document/fiche_elu/3');
INSERT INTO sponsoredlinks_link VALUES(3, 2, 'http://www.mairie.fr/comarquage/3');
INSERT INTO sponsoredlinks_link VALUES(3, 3, 'http://www.mairie.fr/document/article/3');
INSERT INTO sponsoredlinks_link VALUES(4, 1, 'http://www.mairie.fr/document/fiche_elu/4');
INSERT INTO sponsoredlinks_link VALUES(4, 2, 'http://www.mairie.fr/comarquage/4');
INSERT INTO sponsoredlinks_link VALUES(4, 3, 'http://www.mairie.fr/document/article/4');
INSERT INTO sponsoredlinks_link VALUES(5, 1, 'http://www.mairie.fr/document/fiche_elu/5');
INSERT INTO sponsoredlinks_link VALUES(5, 2, 'http://www.mairie.fr/comarquage/5');
INSERT INTO sponsoredlinks_link VALUES(5, 3, 'http://www.mairie.fr/document/article/5');
INSERT INTO sponsoredlinks_link VALUES(6, 1, 'http://www.mairie.fr/document/fiche_elu/6');
INSERT INTO sponsoredlinks_link VALUES(6, 2, 'http://www.mairie.fr/comarquage/6');
INSERT INTO sponsoredlinks_link VALUES(6, 3, 'http://www.mairie.fr/document/article/6');
INSERT INTO sponsoredlinks_link VALUES(7, 1, 'http://www.mairie.fr/document/fiche_elu/7');
INSERT INTO sponsoredlinks_link VALUES(7, 2, 'http://www.mairie.fr/comarquage/7');
INSERT INTO sponsoredlinks_link VALUES(7, 3, 'http://www.mairie.fr/document/article/7');
INSERT INTO sponsoredlinks_link VALUES(8, 1, 'http://www.mairie.fr/document/fiche_elu/8');
INSERT INTO sponsoredlinks_link VALUES(8, 2, 'http://www.mairie.fr/comarquage/8');
INSERT INTO sponsoredlinks_link VALUES(8, 3, 'http://www.mairie.fr/document/article/8');
INSERT INTO sponsoredlinks_link VALUES(11, 1, 'http://www.mairie.fr/document/fiche_elu/11');
INSERT INTO sponsoredlinks_link VALUES(11, 2, 'http://www.mairie.fr/comarquage/11');
INSERT INTO sponsoredlinks_link VALUES(11, 3, 'http://www.mairie.fr/document/article/11');
INSERT INTO sponsoredlinks_link VALUES(12, 1, 'http://www.mairie.fr/document/fiche_elu/12');
INSERT INTO sponsoredlinks_link VALUES(12, 2, 'http://www.mairie.fr/comarquage/12');
INSERT INTO sponsoredlinks_link VALUES(12, 3, 'http://www.mairie.fr/document/article/12');
INSERT INTO sponsoredlinks_link VALUES(13, 1, 'http://www.mairie.fr/document/fiche_elu/13');
INSERT INTO sponsoredlinks_link VALUES(13, 2, 'http://www.mairie.fr/comarquage/13');
INSERT INTO sponsoredlinks_link VALUES(13, 3, 'http://www.mairie.fr/document/article/13');
INSERT INTO sponsoredlinks_link VALUES(14, 1, 'http://www.mairie.fr/document/fiche_elu/14');
INSERT INTO sponsoredlinks_link VALUES(14, 2, 'http://www.mairie.fr/comarquage/14');
INSERT INTO sponsoredlinks_link VALUES(14, 3, 'http://www.mairie.fr/document/article/14');
